### ISSUE TITLE
Merged Contacts not updating correctly. Specifically canonical-vid is not being updated.

### ISSUE THREAD

**Issue by thoughtchad** [singer-io/tap-hubspot#49]
Merged 3000+ contacts yesterday via Merge contact API.

The next day I reviewed the stitch data and the contacts.canonical-vid has not been updated.

The contact in hubspot is merged.
The hubspot getcontact api shows they are merged with correct canonical-vid pointing to the other.
The stitch contacts__merged-vids and contacts__merge-audits tables both reflect that the merge occurred.

But... the none of the contact rows in the stitch contacts table have the new canonical-vid. On all the records that were involved in the merge, the canonical-vid = vid.

The expected result is:
Original State:
   Merge parent
      vid = 1000, canonical-vid = 1000
   Merge child
      vid = 2000, canonical-vid = 2000
Merged State:
   Merge parent
      vid = 1000, canonical-vid = 1000
   Merge child
      vid = 2000, **canonical-vid = 1000**

**Comment by KAllan357** [comment]
Leaving some context from conversations outside of Github:

Example: When a contact with canonical-vid 202 is merged into a contact with canonical-vid 201, the contact with canonical-vid 201 is updated (vid 202 is added to its merged contacts), and the contact with canonical-vid 202 is effectively deleted - it is no longer available from Hubspot's API.

When the tap encounters this scenario it's going to update the parent contact with the merge information, but since the Hubspot API doesn't give us a way to detect that the child was deleted or updated, we don't update the child contact directly.

Our general policy is to keep data in the rawest possible form to ensure that we do not impose assumptions that may not always be true. In this case, Hubspot returns us an updated canonical-vid 201 and no canonical-vid 202 - the behavior is correct.

**Comment by thoughtchad** [comment]
@KAllan357 Deleted is not the correct term. It's still there in the hubspot back end. It's just just rolled up into another vid. There is a reason there is a canonical vid. If hubspot simply deleted the original vid, then they would not need a canonical-vid field, right? 

There is a merged vid data table that the stitch tap creates. It's a fact that the tap does know a vid is 'deleted'. The canonical-vid of the merged vid should be updated by the tap. No one has any need for raw data that is not correct. The whole point of canonical-vid is so that we can determine which which vids to query with a simple canonical-vid=vid. Since the tap does not update this data, we can't use it. We have to do complex sub-queries using the merged vid table.

This is so a 'works-as-designed' closure - If Stitch does not want to improve on the tap then so be it. As a paying customer my expectations for a premium tap is that I don't have to jump through hoops after the data is delivered.

I would request that you please update your documentation so that your paying customers will know that they will have to build additional etl's to modify the 'raw' data plus leverage complex sql work-arounds to ensure that the data they are reporting on is correct; because right now the data that stitch delivers is not correct.

I'd love to help out with the open source tap - but stitch needs to tighten up the process and docs for external developers to get involved. Build some docker containers or leverage something like nanobox.io so it's stupid simple to test and drop a pull request. Lastly, to test a tap against my paid for account uses up our precious paid for rows. So, I'm paying stitch for services, then paying my own developers to fix stuff, and also paying for the rows to dev/test as well. Right?
